{% set name = "pythia-datasets" %}
{% set version = "2021.9.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19fcb86b0db71aa3251dcab528b51bf66639e2dc3c8654d6fc80b8a3379ac650

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pooch

test:
  imports:
    - pythia_datasets
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --pyargs pythia_datasets

about:
  home: https://github.com/ProjectPythia/pythia-datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Data repository for Project Pythia examples/notebooks'
  doc_url: https://github.com/ProjectPythia/pythia-datasets
  dev_url: https://github.com/ProjectPythia/pythia-datasets

extra:
  recipe-maintainers:
    - brian-rose
    - andersy005
    - mgrover1
