{% set name = "pythia-datasets" %}
{% set version = "2026.2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7ff7427d2ad99b6eca561104eac2c51f401584c380a96b6229599dd045f85be4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatch
  run:
    - python >={{ python_min }}
    - pooch

test:
  imports:
    - pythia_datasets
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check
    - pytest --pyargs pythia_datasets

about:
  home: https://github.com/ProjectPythia/pythia-datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Data repository for Project Pythia examples/notebooks'
  doc_url: https://github.com/ProjectPythia/pythia-datasets
  dev_url: https://github.com/ProjectPythia/pythia-datasets

extra:
  recipe-maintainers:
    - brian-rose
    - andersy005
    - mgrover1
